### ISSUE TITLE
mobile and tablets layouts

### ISSUE THREAD

**Issue by dasmike** [AnatolyFeteleu/CV#4]
на телефонах и планшетах верстка плывет
![2016-08-24 15 32 13](https://cloud.githubusercontent.com/assets/9625184/17923835/3d75145e-6a10-11e6-8bd6-19d1ede08b08.png)
![2016-08-24 15 34 15](https://cloud.githubusercontent.com/assets/9625184/17923836/3d7651e8-6a10-11e6-9eab-685923087c4b.png)

**Comment by AnatolyFeteleu** [comment]
Должно всё корректно отображаться
