### ISSUE TITLE
table

### ISSUE THREAD

**Issue by dasmike** [AnatolyFeteleu/CV#9]
![2016-08-24 16 33 03](https://cloud.githubusercontent.com/assets/9625184/17925808/9b938cfc-6a18-11e6-91a9-c935eea5ce1f.png)

что за таблица? для чего она нужна, и что за странное у нее позиционирование?

**Comment by dasmike** [comment]
такие огромные отступы у нее к тому же
![2016-08-24 16 35 13](https://cloud.githubusercontent.com/assets/9625184/17925855/d06ca4b8-6a18-11e6-94c9-28e71373ad85.png)

**Comment by dasmike** [comment]
![image](https://cloud.githubusercontent.com/assets/9625184/17926208/49e1feaa-6a1a-11e6-9df3-48937123dbb7.png)

**Comment by AnatolyFeteleu** [comment]
Таблицу поправил

**Comment by dasmike** [comment]
=) в данном случае можно было обойтись вообще без таблицы)

**Comment by dasmike** [comment]
![image](https://cloud.githubusercontent.com/assets/9625184/17941237/ac6ead92-6a5c-11e6-88a9-9d9f427ffc6d.png)
![image](https://cloud.githubusercontent.com/assets/9625184/17941290/d8058d9a-6a5c-11e6-85ac-6c7db89cc8f7.png)
![image](https://cloud.githubusercontent.com/assets/9625184/17941320/fcb38b88-6a5c-11e6-87f6-23acbbc31b9b.png)
структура к тому же у нее странная) смотри где область одной ячейки, где область второй ячейки. а область всей строки совсем в другом месте показана =)
